force-app/main/default/objects/Assignment_Group__c/Assignment_Group__c.object-meta.xml
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Assignment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_Group_Member__c/Assignment_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Assignment Group Member</label>
    <nameField>
        <displayFormat>AGM-{000000}</displayFormat>
        <label>Assignment Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Address__c/Dispatch_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Customer Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Addresses</relationshipLabel>
    <relationshipName>Dispatch_Address</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch_Address__c/fields/SAP_Update_Customer__c.field-meta.xml
<CustomField>
    <fullName>SAP_Update_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAP Update Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group_Member__c/Group_Member__c.object-meta.xml
<CustomObject>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{000000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI_Target__c/KPI_Target__c.object-meta.xml
<CustomObject>
    <label>KPI Target</label>
    <nameField>
        <displayFormat>KTN-{0000}</displayFormat>
        <label>KPI Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI_Target__c/fields/Monthly_Beat_Plan__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Beat_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly Beat Plan</label>
    <referenceTo>Monthly_Beat_Plan__c</referenceTo>
    <relationshipLabel>KPI Targets</relationshipLabel>
    <relationshipName>KPI_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KPI_Target__c/fields/Roles_and_KPI__c.field-meta.xml
<CustomField>
    <fullName>Roles_and_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Roles and KPI</label>
    <referenceTo>Roles_and_KPI__c</referenceTo>
    <relationshipLabel>KPI Targets</relationshipLabel>
    <relationshipName>KPI_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>My Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Beat_Plan__c/Monthly_Beat_Plan__c.object-meta.xml
<CustomObject>
    <label>Monthly Beat Plan</label>
    <nameField>
        <displayFormat>MBP-{0000}</displayFormat>
        <label>Monthly Beat Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Beat Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Month_year__c.field-meta.xml
<CustomField>
    <fullName>Month_year__c</fullName>
    <label>Month year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monthly_Beat_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roles_and_KPI__c/Roles_and_KPI__c.object-meta.xml
<CustomObject>
    <label>Roles and KPI</label>
    <nameField>
        <label>Roles and KPIs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles and KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Roles_and_KPI__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Roles_and_KPIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>RN-{000}</displayFormat>
        <label>Route Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Predefined_Area__c.field-meta.xml
<CustomField>
    <fullName>Predefined_Area__c</fullName>
    <label>Predefined Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Name_del__c.field-meta.xml
<CustomField>
    <fullName>Route_Name_del__c</fullName>
    <label>Route Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BTM Layout</fullName>
            </value>
            <value>
                <fullName>HSR Layout</fullName>
            </value>
            <value>
                <fullName>Sarjapur</fullName>
            </value>
            <value>
                <fullName>JP Nagar</fullName>
            </value>
            <value>
                <fullName>Jaya Nagar</fullName>
            </value>
            <value>
                <fullName>Uttam Nagar</fullName>
            </value>
            <value>
                <fullName>Janak Puri</fullName>
            </value>
            <value>
                <fullName>Tilak Pul</fullName>
            </value>
            <value>
                <fullName>Jeevan Park</fullName>
            </value>
            <value>
                <fullName>Dabri More</fullName>
            </value>
            <value>
                <fullName>Seetapuri extension</fullName>
            </value>
            <value>
                <fullName>BrokeField</fullName>
                <isActive>false</isActive>
                <label>BrokeField</label>
            </value>
            <value>
                <fullName>Cabbon Park</fullName>
                <isActive>false</isActive>
                <label>Cabbon Park</label>
            </value>
            <value>
                <fullName>Electronic City</fullName>
                <isActive>false</isActive>
                <label>Electronic City</label>
            </value>
            <value>
                <fullName>Hebbal</fullName>
                <isActive>false</isActive>
                <label>Hebbal</label>
            </value>
            <value>
                <fullName>KR Puram</fullName>
                <isActive>false</isActive>
                <label>KR Puram</label>
            </value>
            <value>
                <fullName>Kormangala</fullName>
                <isActive>false</isActive>
                <label>Kormangala</label>
            </value>
            <value>
                <fullName>LalBagh</fullName>
                <isActive>false</isActive>
                <label>LalBagh</label>
            </value>
            <value>
                <fullName>MG Road</fullName>
                <isActive>false</isActive>
                <label>MG Road</label>
            </value>
            <value>
                <fullName>MICO Layout</fullName>
                <isActive>false</isActive>
                <label>MICO Layout</label>
            </value>
            <value>
                <fullName>Madiwala</fullName>
                <isActive>false</isActive>
                <label>Madiwala</label>
            </value>
            <value>
                <fullName>Marathalli</fullName>
                <isActive>false</isActive>
                <label>Marathalli</label>
            </value>
            <value>
                <fullName>Panduranga Nagar</fullName>
                <isActive>false</isActive>
                <label>Panduranga Nagar</label>
            </value>
            <value>
                <fullName>Richmond Circle</fullName>
                <isActive>false</isActive>
                <label>Richmond Circle</label>
            </value>
            <value>
                <fullName>Whitefield</fullName>
                <isActive>false</isActive>
                <label>Whitefield</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>VISIT-{0000}</displayFormat>
        <label>Visitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit</relationshipLabel>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Actual_visit_date__c.field-meta.xml
<CustomField>
    <fullName>Actual_visit_date__c</fullName>
    <label>Actual visit date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/KPI_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Target</label>
    <referenceTo>KPI_Target__c</referenceTo>
    <relationshipLabel>Visit</relationshipLabel>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Monthly_Beat_Plan__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Beat_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly Beat Plan</label>
    <referenceTo>Monthly_Beat_Plan__c</referenceTo>
    <relationshipLabel>Visit</relationshipLabel>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Visit</relationshipLabel>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(AND(NOT(ISNULL(Visit_Plan__r.End_Location__c)), ISNULL(Check_Out__c)), &apos;LAPSE&apos;, IF(AND(ISNULL(CheckIn__c),ISNULL(Check_Out__c)) , &apos;PENDING&apos;, IF(AND(NOT(ISNULL(CheckIn__c)),ISNULL(Check_Out__c)),&apos;INPROGRESS&apos;,&apos;COMPLETED&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Weekly_Beat_Plan__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Beat_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weekly Beat Plan</label>
    <referenceTo>Weekly_Beat_Plan__c</referenceTo>
    <relationshipLabel>Visit</relationshipLabel>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Weekly_Beat_Plan__c/Weekly_Beat_Plan__c.object-meta.xml
<CustomObject>
    <label>Weekly Beat Plan</label>
    <nameField>
        <displayFormat>WBP-{0000}</displayFormat>
        <label>Weekly Beat Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Beat Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weekly_Beat_Plan__c/fields/Monthly_Beat_Plan__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Beat_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly Beat Plan</label>
    <referenceTo>Monthly_Beat_Plan__c</referenceTo>
    <relationshipLabel>Weekly Beat Plans</relationshipLabel>
    <relationshipName>Weekly_Beat_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MonthlyVisitViewerControllerTest.cls
@IsTest(SeeAllData=true)
public class MonthlyVisitViewerControllerTest {
    
    @isTest
    public static void fetchPageDataTest() {
        
        List<Visit__c> getAllvisitRecordList = new List<Visit__c>();
        List<Monthly_Beat_Plan__c> mbpRecList = new List<Monthly_Beat_Plan__c>();
        List<String> routeList = new List<String>();
        List<Assignment_Group_Member__c> asigGroupMemberRecList = new List<Assignment_Group_Member__c>();
        
        Location__c locaRec = new Location__c();
        locaRec.Name = 'Test Location';
        insert locaRec;
        
        Account accRec = new Account();
        accRec.Name = 'Test FSL';
        accRec.BillingStreet = 'JP nagar';
        accRec.BillingCity = 'Bangalore';
        accRec.SAP_Update_Customer__c = true;
        //accRec.Location__c = locaRec.Id;
        insert accRec;
        
        Contact conRec = new Contact();
        conRec.LastName = 'test Contact';
        conRec.CurrencyIsoCode = 'INR';
        conRec.Email = 'Test@email.com';
		conRec.Phone = '928468939';
        conRec.AccountId = accRec.Id;
        insert conRec;
        
        Lead ledRec = new Lead();
        ledRec.FirstName = 'Test';
        ledRec.LastName = 'Lead';
        ledRec.AccountId__c = accRec.Id;
        ledRec.Company = 'Test PVT.';
        ledRec.CurrencyIsoCode = 'INR';
        ledRec.Status = 'Sales Qualification';
        //ledRec.Location__c = locaRec.Id;
        insert ledRec;
        
        Assignment_Group__c asigGroupRec = new Assignment_Group__c();
        asigGroupRec.Name = 'Test AssigGroup';
        insert asigGroupRec;
        
        Assignment_Group_Member__c asigGroupMemberRec = new Assignment_Group_Member__c();
        asigGroupMemberRec.Assignment_Group__c = asigGroupRec.Id;
        asigGroupMemberRec.Assignment_Id__c = 0020;
        asigGroupMemberRec.Group_Member__c = UserInfo.getUserId();
        insert asigGroupMemberRec;
        asigGroupMemberRecList.add(asigGroupMemberRec);
        
        Dispatch_Address__c disAddress = new Dispatch_Address__c();
        disAddress.Account__c = accRec.Id;
        
        Route__c routeRec = new Route__c();
        routeRec.Predefined_Area__c = 'test';
        routeRec.Route_Name_del__c = 'JP Nagar';
        insert routeRec;
        routeList.add(routeRec.Route_Name_del__c);
        
        Roles_and_KPI__c roleKpiRec = new Roles_and_KPI__c();
        roleKpiRec.Name = 'Test Role and Kpi';
        roleKpiRec.Sales_User__c = UserInfo.getUserId();
        insert roleKpiRec;
        
        KPI_Target__c kpiTarRec = new KPI_Target__c();
        kpiTarRec.Roles_and_KPI__c = roleKpiRec.Id;
        insert kpiTarRec;
        
        Visit__c visirtRec = new Visit__c();
        visirtRec.Actual_visit_date__c = System.today();
        visirtRec.KPI_Target__c = kpiTarRec.Id;
        visirtRec.Account__c = accRec.Id;
        insert visirtRec;
        getAllvisitRecordList.add(visirtRec);
        
        Monthly_Beat_Plan__c mbpRec = new Monthly_Beat_Plan__c();
        mbpRec.Approval_Status__c = 'Approved';
        mbpRec.Start_Date__c = Date.newInstance(2023, 11, 9);
        mbpRec.CurrencyIsoCode = 'INR';
        mbpRec.Status__c = 'Approved';
        mbpRec.Month_year__c = '2023';
        mbpRec.Month_Name__c = 'November';
        insert mbpRec;
        
        Weekly_Beat_Plan__c wbpRec = new Weekly_Beat_Plan__c();
        wbpRec.Monthly_Beat_Plan__c = mbpRec.Id;
        insert wbpRec;
        test.startTest();
        
        MonthlyVisitViewerController.getcurrentUserRoutes();
        MonthlyVisitViewerController.fetchPageData('2023-November-11');
        MonthlyVisitViewerController.getAllLocationRecords();
        MonthlyVisitViewerController.getSelectedObjectRecord(ledRec.Id,locaRec.Id);
        MonthlyVisitViewerController.getSelectedAccountRecords(accRec.Id,locaRec.Id);
        MonthlyVisitViewerController.createVisits(getAllvisitRecordList);
        MonthlyVisitViewerController.showKpi(visirtRec.Id);
        MonthlyVisitViewerController.tagKIPToVisit(visirtRec.Id,kpiTarRec.Id);
        MonthlyVisitViewerController.getCurrentRecordGeoLocation(ledRec.Id);
        MonthlyVisitViewerController.getCurrentRecordGeoLocation(accRec.Id);
        MonthlyVisitViewerController.createVisitObjectTypev1(ledRec.Id, '2023-11-11', '12.890992','77.570802','6:32:00','7:32:00');
        MonthlyVisitViewerController.createVisitObjectTypev1(accRec.Id, '2023-11-11', '12.890992','77.570802','6:32:00','7:32:00');
        MonthlyVisitViewerController.createVisitObjectType(ledRec.Id, '2023-11-11', '12.890992','77.570802');
        MonthlyVisitViewerController.createVisitObjectType(accRec.Id, '2023-11-11', '12.890992','77.570802');
        MonthlyVisitViewerController.getUserVisits('JP Nagar');
        MonthlyVisitViewerController.fetchGroupmemeber('JP Nagar');
        MonthlyVisitViewerController.deleteEvent(visirtRec.Id);
    }
    
    
   
}