force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Sample/Project/Application</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Project/Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Submitted_To_SAP_Optiva__c.field-meta.xml
<CustomField>
    <fullName>Submitted_To_SAP_Optiva__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Project__c/recordTypes/Sample.recordType-meta.xml
<RecordType>
    <fullName>Sample</fullName>
    <active>true</active>
    <label>Sample</label>
</RecordType>

force-app/main/default/classes/Optiva_LWC_NPD_Controller.cls
public without sharing class Optiva_LWC_NPD_Controller {
    
    @AuraEnabled
    public static Project__c getRecordTypeName(String recId){
        try {
            return [Select Id,RecordType.name,Submitted_To_SAP_Optiva__c FROM Project__c where Id =:recId];
        } catch (Exception e) {
            HandleBusinessException.captureError('Optiva_LWC_NPD_Controller','getRecordTypeName',e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Map<String,String> syncSample(String recId, String recType){
        try {
            if(recType=='Project'){
                return Optiva_Callout.projectCreation(recId);
            }else if(recType=='Application'){
                return Optiva_Callout.applicationCreation(recId);
            }else if(recType=='Sample'){
                return Optiva_Callout.sampleCreation(recId); // create sample in optiva or create task for SAP
            }else{
                System.debug('SOSOSOS----'+recType);
                return Optiva_Callout.techDocCreation(recId);
            }
        } catch (Exception e) {
            HandleBusinessException.captureError('Optiva_LWC_NPD_Controller','syncSample',e);
            throw new AuraHandledException(e.getMessage());
        }
    }
}