force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Sample/Project/Application</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Project/Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Use_Applications__c.field-meta.xml
<CustomField>
    <fullName>End_Use_Applications__c</fullName>
    <label>End Use Applications</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>End_Use_category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potato Chips</fullName>
            </value>
            <value>
                <fullName>Finger/Extruded Snacks</fullName>
            </value>
            <value>
                <fullName>Pellets/Fryums</fullName>
            </value>
            <value>
                <fullName>Puffed Snacks</fullName>
            </value>
            <value>
                <fullName>Tortilla Chips</fullName>
            </value>
            <value>
                <fullName>Namkeens and Other traditional</fullName>
            </value>
            <value>
                <fullName>Popcorn</fullName>
            </value>
            <value>
                <fullName>Nuts, Seeds and Trail Mixes</fullName>
            </value>
            <value>
                <fullName>White Noodles</fullName>
            </value>
            <value>
                <fullName>Brown Noodles</fullName>
            </value>
            <value>
                <fullName>Atta/Oats/Multigrain Noodles</fullName>
            </value>
            <value>
                <fullName>Pasta</fullName>
            </value>
            <value>
                <fullName>Oats-based</fullName>
            </value>
            <value>
                <fullName>Millets-based</fullName>
            </value>
            <value>
                <fullName>Grain-based</fullName>
            </value>
            <value>
                <fullName>Instant</fullName>
            </value>
            <value>
                <fullName>Cook-up</fullName>
            </value>
            <value>
                <fullName>RTD</fullName>
            </value>
            <value>
                <fullName>Biscuits and Cookies</fullName>
            </value>
            <value>
                <fullName>Crackers</fullName>
            </value>
            <value>
                <fullName>Bread and Bread Products</fullName>
            </value>
            <value>
                <fullName>Cakes and Pastries</fullName>
            </value>
            <value>
                <fullName>Wafers</fullName>
            </value>
            <value>
                <fullName>Creams and fills</fullName>
            </value>
            <value>
                <fullName>Candies and Lollipop</fullName>
            </value>
            <value>
                <fullName>Medicated Confectionery (Lozenges)</fullName>
            </value>
            <value>
                <fullName>Mints</fullName>
            </value>
            <value>
                <fullName>Toffees, Caramels and Noughat</fullName>
            </value>
            <value>
                <fullName>Pastilles, Jellies and Chews</fullName>
            </value>
            <value>
                <fullName>Gums</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Use_category__c.field-meta.xml
<CustomField>
    <fullName>End_Use_category__c</fullName>
    <inlineHelpText>Choose end use category and the end use application will be based on category opted.</inlineHelpText>
    <label>End Use category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Baked Goods</fullName>
            </value>
            <value>
                <fullName>Breakfast Cereals</fullName>
            </value>
            <value>
                <fullName>Chilled and Frozen Foods</fullName>
            </value>
            <value>
                <fullName>Confectionery</fullName>
            </value>
            <value>
                <fullName>Dairy and Alternatives</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Food Service</fullName>
            </value>
            <value>
                <fullName>Noodles and Pasta</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Soups</fullName>
            </value>
            <value>
                <fullName>Sauces and Meals</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Bakery</fullName>
                <isActive>false</isActive>
                <label>Bakery</label>
            </value>
            <value>
                <fullName>Beverage</fullName>
                <isActive>false</isActive>
                <label>Beverage</label>
            </value>
            <value>
                <fullName>Dairy</fullName>
                <isActive>false</isActive>
                <label>Dairy</label>
            </value>
            <value>
                <fullName>Oral Care</fullName>
                <isActive>false</isActive>
                <label>Oral Care</label>
            </value>
            <value>
                <fullName>Pharma</fullName>
                <isActive>false</isActive>
                <label>Pharma</label>
            </value>
            <value>
                <fullName>Savoury</fullName>
                <isActive>false</isActive>
                <label>Savoury</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <inlineHelpText>Choose the product family</inlineHelpText>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPD</fullName>
            </value>
            <value>
                <fullName>SPD</fullName>
            </value>
            <value>
                <fullName>Natural colour</fullName>
                <label>COLOR</label>
            </value>
            <value>
                <fullName>FLAVOUR</fullName>
            </value>
            <value>
                <fullName>PLANT BASED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SampleTriggerTest.cls
@isTest
public class SampleTriggerTest {
    @isTest(SeeAllData=true)
    private static void run(){
        Database.SaveResult dsr;
        Account acc = new Account();
        acc.Name = 'DUMMY ACCOUNT';
        Insert acc;
        
        Project__c ud = new Project__c();
        ud.Account__c = acc.Id;
        ud.Product_Family__c = 'CPD';
        ud.End_Use_Applications__c = 'Popcorn';
        ud.End_Use_category__c = 'Snacks';
        insert ud;
        ud.Application_Name__c = 'Test';
        update ud;
    }
}