force-app/main/default/objects/Project_Quotient__c/Project_Quotient__c.object-meta.xml
<CustomObject>
    <label>Project Quotient</label>
    <nameField>
        <displayFormat>PQ-{0000}</displayFormat>
        <label>Project Quotient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Quotients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Quotient__c/fields/Sample_Project_Application__c.field-meta.xml
<CustomField>
    <fullName>Sample_Project_Application__c</fullName>
    <label>Sample/Project/Application</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Quotients</relationshipLabel>
    <relationshipName>Project_Quotients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Quotient__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In-Discussion</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Line_Item__c/Sample_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sample Line Item</label>
    <nameField>
        <displayFormat>SLI -{000000}</displayFormat>
        <label>Sample Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Line_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>IF( Product__r.Name!= null, Product__r.Name,  IF(OPTIVA_Recipe__r.Name!= null, 
    OPTIVA_Recipe__r.Name,  Project_Quotient__r.Name) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Line_Item__c/fields/Project_Quotient__c.field-meta.xml
<CustomField>
    <fullName>Project_Quotient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Quotient</label>
    <referenceTo>Project_Quotient__c</referenceTo>
    <relationshipLabel>Sample Line Items</relationshipLabel>
    <relationshipName>Sample_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Line_Item__c/fields/Sample__c.field-meta.xml
<CustomField>
    <fullName>Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Sample Line Items</relationshipLabel>
    <relationshipName>Sample_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Line_Item__c/fields/Sample_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Sample_Request_Status__c</fullName>
    <label>Sample Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Sampling</fullName>
            </value>
            <value>
                <fullName>Sample Dispatched</fullName>
            </value>
            <value>
                <fullName>Sample Received By Client</fullName>
            </value>
            <value>
                <fullName>Sample Accepted</fullName>
            </value>
            <value>
                <fullName>Sample Rejected</fullName>
            </value>
            <value>
                <fullName>Need Amendments</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
                <isActive>false</isActive>
                <label>Application Accepted</label>
            </value>
            <value>
                <fullName>Application Project Ready</fullName>
                <isActive>false</isActive>
                <label>Application Project Ready</label>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
                <isActive>false</isActive>
                <label>Application Rejected</label>
            </value>
            <value>
                <fullName>Approved by R&amp;D</fullName>
                <isActive>false</isActive>
                <label>Approved by R&amp;D</label>
            </value>
            <value>
                <fullName>Forwarded Sample Detail to Client</fullName>
                <isActive>false</isActive>
                <label>Forwarded Sample Detail to Client</label>
            </value>
            <value>
                <fullName>Project Accepted</fullName>
                <isActive>false</isActive>
                <label>Project Accepted</label>
            </value>
            <value>
                <fullName>Project Ready to Dispatch</fullName>
                <isActive>false</isActive>
                <label>Project Ready to Dispatch</label>
            </value>
            <value>
                <fullName>Project Rejected</fullName>
                <isActive>false</isActive>
                <label>Project Rejected</label>
            </value>
            <value>
                <fullName>Rejected by R&amp;D</fullName>
                <isActive>false</isActive>
                <label>Rejected by R&amp;D</label>
            </value>
            <value>
                <fullName>Sample Ready to Dispatch</fullName>
                <isActive>false</isActive>
                <label>Sample Ready to Dispatch</label>
            </value>
            <value>
                <fullName>Submitted for Application</fullName>
                <isActive>false</isActive>
                <label>Submitted for Application</label>
            </value>
            <value>
                <fullName>Submitted for Project</fullName>
                <isActive>false</isActive>
                <label>Submitted for Project</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ShowAndUpdateProjectQuotients.cls
public class ShowAndUpdateProjectQuotients {
    @AuraEnabled
    public static List<Project_Quotient__c> showProjectQuotientRec(string proRecId){
        List<Project_Quotient__c> prolist;
        if(proRecId != null){
            prolist   = [Select Id, Name, Stage__c, Lost_Reason__c from Project_Quotient__c where Sample_Project_Application__c =: proRecId];
            if(prolist.size()>0){
                return prolist;
            }  
            
        }
        return null;
    }
    @AuraEnabled
    public static List<String> getStagePicklistValues() {
        Schema.DescribeFieldResult fieldResult = Project_Quotient__c.Stage__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        List<String> StageValues = new List<String>();
        
        for (Schema.PicklistEntry entry : picklistValues) {
            StageValues.add(entry.getValue());
        }
        
        return StageValues;
    }
    
    @AuraEnabled
    public static string updateProjectQuotientValues( List<Project_Quotient__c> projectlist){
        try{
            update projectlist;
            return 'success';
        }
        catch(exception e){
            system.debug('Error Msg :: ' + e.getMessage());
            system.debug('Error Line No :: ' + e.getLineNumber());
            return e.getMessage();
        }
    }
    
     @AuraEnabled
    public static List<String> getSampleStatusPicklistValues() {
        Schema.DescribeFieldResult fieldResult = Sample_Line_Item__c.Sample_Request_Status__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        List<String> StageValues = new List<String>();
        
        for (Schema.PicklistEntry entry : picklistValues) {
            StageValues.add(entry.getValue());
        }
        
        return StageValues;
    }
     @AuraEnabled
    public static List<Sample_Line_Item__c> showSamplelineRec(string proRecId){
        List<Sample_Line_Item__c> samplelist;
        if(proRecId != null){
            samplelist   = [Select id, Product_Name__c,Sample_Request_Status__c  from Sample_Line_Item__c where Sample__c =: proRecId];
            if(samplelist.size()>0){
                return samplelist;
            }  
            
        }
        return null;
    }
    @AuraEnabled
    public static string updateSamplelineItemValues( List<Sample_Line_Item__c> samplelineIemlist){
        try{
            update samplelineIemlist;
            return 'success';
        }
        catch(exception e){
            system.debug('Error Msg :: ' + e.getMessage());
            system.debug('Error Line No :: ' + e.getLineNumber());
            return e.getMessage();
        }
    }
}