force-app/main/default/objects/Day_Visit_Plan__c/Day_Visit_Plan__c.object-meta.xml
<CustomObject>
    <label>Day Visit Plan</label>
    <nameField>
        <displayFormat>DVP-{0000}</displayFormat>
        <label>Day Visit Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Day Visit Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Monthly_Travel_Expense__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Travel_Expense__c</fullName>
    <label>Monthly Travel Expense</label>
    <referenceTo>Monthly_Travel_Expense__c</referenceTo>
    <relationshipLabel>Day Visit Plan</relationshipLabel>
    <relationshipName>Day_Visit_Plan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KPI_Target__c/KPI_Target__c.object-meta.xml
<CustomObject>
    <label>KPI Target</label>
    <nameField>
        <displayFormat>KTN-{0000}</displayFormat>
        <label>KPI Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI_Target__c/fields/Roles_and_KPI__c.field-meta.xml
<CustomField>
    <fullName>Roles_and_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Roles and KPI</label>
    <referenceTo>Roles_and_KPI__c</referenceTo>
    <relationshipLabel>KPI Targets</relationshipLabel>
    <relationshipName>KPI_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Travel_Expense__c/Monthly_Travel_Expense__c.object-meta.xml
<CustomObject>
    <label>Monthly Travel Expense</label>
    <nameField>
        <label>Monthly Travel Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Travel Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Roles_and_KPI__c/Roles_and_KPI__c.object-meta.xml
<CustomObject>
    <label>Roles and KPI</label>
    <nameField>
        <label>Roles and KPIs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles and KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>VISIT-{0000}</displayFormat>
        <label>Visitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit</relationshipLabel>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Actual_visit_date__c.field-meta.xml
<CustomField>
    <fullName>Actual_visit_date__c</fullName>
    <label>Actual visit date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/KPI_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Target</label>
    <referenceTo>KPI_Target__c</referenceTo>
    <relationshipLabel>Visit</relationshipLabel>
    <relationshipName>Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_visit_date__c.field-meta.xml
<CustomField>
    <fullName>Planned_visit_date__c</fullName>
    <label>Planned visit date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TodayTaskAuraControllerTest.cls
@isTest(SeeAllData=true)
public class TodayTaskAuraControllerTest {

    @isTest
    public static void createVisitActivityTest(){
        
        List<Visit__c> getAllvisitRecordList = new List<Visit__c>();
        
        Account accRec = new Account();
        accRec.Name = 'Test FSL';
        accRec.BillingStreet = 'JP nagar';
        accRec.BillingCity = 'Bangalore';
        accRec.SAP_Update_Customer__c = true;
        insert accRec;
        
        Opportunity oppRec = new Opportunity();
        oppRec.Name = 'Test Opp';
        oppRec.CloseDate = system.today();
        oppRec.CurrencyIsoCode = 'INR';
        oppRec.Annual_Volume_Full__c = 12.01;
        oppRec.Annual_Volume_in_units__c = 'Kg';
        oppRec.End_Use_Category__c = 'Beverages';
        oppRec.End_Use_Application__c = 'Beer';
        oppRec.Target_Price_Kg__c = 30;
        oppRec.AccountId = accRec.Id;
        oppRec.StageName = 'New';
        insert oppRec;
        
        Task taskRec = new Task();
        taskRec.Subject = 'Test';
        insert taskRec;
        
        Case caseRec = new Case();
        caseRec.Subject = 'Testing Subject Case';
        caseRec.Status = 'New';
        caseRec.Origin = 'Email';
        caseRec.Description = 'Test Description';
        insert caseRec;
        
        Roles_and_KPI__c roleKpiRec = new Roles_and_KPI__c();
        roleKpiRec.Name = 'Test Role and Kpi';
        insert roleKpiRec;
        
        KPI_Target__c kpiTarRec = new KPI_Target__c();
        kpiTarRec.Roles_and_KPI__c = roleKpiRec.Id;
        insert kpiTarRec;
        
        Visit__c visirtRec = new Visit__c();
        visirtRec.Actual_visit_date__c = System.today();
        visirtRec.KPI_Target__c = kpiTarRec.Id;
        visirtRec.Account__c = accRec.Id;
        visirtRec.Planned_visit_date__c = system.today();
        visirtRec.Assigned_User__c = UserInfo.getUserId();
        insert visirtRec;
        getAllvisitRecordList.add(visirtRec);
        
        Monthly_Travel_Expense__c mteRec = new Monthly_Travel_Expense__c();
        mteRec.Name = 'Test';
        insert mteRec;
        
        Day_Visit_Plan__c dvpRec= new Day_Visit_Plan__c();
        dvpRec.Start_Date__c= System.today();
        dvpRec.Monthly_Travel_Expense__c= mteRec.Id;
        dvpRec.End_Location__Latitude__s = 12.890992;
        dvpRec.End_Location__Longitude__s = 77.570802;
        insert dvpRec;
        
        TodayTaskAuraController.createVisitActivity(oppRec.Id,visirtRec.Id);
        TodayTaskAuraController.getAllVisitTodays('11-11-2023');
        TodayTaskAuraController.getSelectedVisitDetails(visirtRec.Id);
        TodayTaskAuraController.StartDayVisitForVistitRecord('12.890992','77.570802',getAllvisitRecordList);
        TodayTaskAuraController.updateEndDayVisitRecord('12.890992','77.570802');
        TodayTaskAuraController.updateAmendVisitRecord(visirtRec);
        TodayTaskAuraController.saveTask(taskRec);
        TodayTaskAuraController.LogCall(taskRec);
        TodayTaskAuraController.saveOpportunity(oppRec);
        TodayTaskAuraController.saveCase(caseRec);
    }
}