force-app/main/default/objects/Day_Visit_Plan__c/Day_Visit_Plan__c.object-meta.xml
<CustomObject>
    <label>Day Visit Plan</label>
    <nameField>
        <displayFormat>DVP-{0000}</displayFormat>
        <label>Day Visit Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Day Visit Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>MONTH( DATEVALUE(Start_Date__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Month_Name__c.field-meta.xml
<CustomField>
    <fullName>Month_Name__c</fullName>
    <label>Month Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <label>Month Year</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Service_Executive__c.field-meta.xml
<CustomField>
    <fullName>Service_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Day_Visit_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Total_Covered_Distance__c.field-meta.xml
<CustomField>
    <fullName>Total_Covered_Distance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Covered Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Total_Distance__c.field-meta.xml
<CustomField>
    <fullName>Total_Distance__c</fullName>
    <formula>DISTANCE( Start_Location__c , End_Location__c  , &apos;km&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Day_Visit_Plan__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>YEAR(DATEVALUE( Start_Date__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/Monthly_Beat_Plan__c.object-meta.xml
<CustomObject>
    <label>Monthly Beat Plan</label>
    <nameField>
        <displayFormat>MBP-{0000}</displayFormat>
        <label>Monthly Beat Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Beat Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>MONTH( Start_Date__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Month_year__c.field-meta.xml
<CustomField>
    <fullName>Month_year__c</fullName>
    <label>Month year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monthly_Beat_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Beat_Plan__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>TEXT( YEAR(Start_Date__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Scheduler_Insight_MonthYear_handler.cls
public class Scheduler_Insight_MonthYear_handler {
    
    @AuraEnabled
    public static returnDAta getMonthBeatPlan(String month,string year){
         System.debug('month ==>'+month);
         System.debug('year ==>'+year);
        returnDAta mainData = new returnDAta();
        Monthly_Beat_Plan__c getAllMBPList = [Select Id,Name,Sales_User__c,Sales_User__r.Name,CreatedDate,Month__c,Month_Name__c,Year__c,Status__c From Monthly_Beat_Plan__c Where Sales_User__c =: userInfo.getUserId() AND Month_year__c=:year AND Month_Name__c=:month LIMIT 1];
        mainData.mbplRecord=getAllMBPList;
        System.debug('getAllMBPList ==>'+getAllMBPList.Sales_User__r.Name);
        System.debug('getAllMBPList ==>'+getAllMBPList);
        mainData.approvalData=ApprovalDetailsHelper.getActualApprovalDetails(getAllMBPList.id);
        system.debug('mainData--->'+mainData);
        return mainData;
    }
    
    @AuraEnabled
    Public static List<Day_Visit_Plan__c> getMonthlyRecord(String month,string year){
        List<Day_Visit_Plan__c> getAllDayVisitPlanRecList = [Select Id,Start_Date__c,End_Date__c,Total_Distance__c, Total_Covered_Distance__c,CreatedDate From Day_Visit_Plan__c where Service_Executive__c =: userInfo.getUserId() AND Month_year__c=:year AND Month_Name__c=:month];
        return getAllDayVisitPlanRecList;
    }
    
    PUblic class returnDAta{
        @AuraEnabled
        Public Monthly_Beat_Plan__c mbplRecord;
        @AuraEnabled
        Public ApprovalDetailsHelper.ApprovalUserDetails approvalData;
    }
}